spring:
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9093
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              record:
                value:
                  serde: org.apache.kafka.commmon.serialization.Serdes$IntegerSerde
#      client-id: akfak


spring.cloud.stream.bindings:
  input:
    destination: akfak
    consumer:
      headerMode: raw
  record:
    destionation: record
    consumer:
      headerMode: raw
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9093

server:
  port: 8080