spring:
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9093
#      client-id: akfak

spring.cloud.stream:
  bindings:
    stringStream:
      destination: string
      consumer:
        headerMode: raw
        useNativeDecoding: true
    avroStream:
      destination: avro
      consumer:
        headerMode: raw
        useNativeDecoding: true
    intStream:
      destination: int
      consumer:
        headerMode: raw
        useNativeDecoding: true
  kafka:
    streams:
      binder:
        brokers: localhost:9093
        configuration:
          schema.registry.url: http://localhost:8081
          default:
            key:
              serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value:
              serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        intStream:
          consumer.valueSerde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
        avroStream:
          consumer:
            valueSerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
            useNativeEncoding: true
          producer:
            valueSerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
            useNativeEncoding: true


server:
  port: 8080