spring:
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9093
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#      client-id: akfak

#spring.cloud.stream.bindings.output.contentType: application/json
#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
#spring.cloud.stream.kafka.streams:
#  binder.configuration:
#    key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#    value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#  bindings.output.producer:
#    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
#    valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde

spring.cloud.stream.bindings.input:
  destination: akfak
  consumer:
    headerMode: raw
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9093

server:
  port: 8080