spring:
  kafka:
    consumer:
      group-id: prozess
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9093

spring.cloud.stream:
  bindings:
    request:
      group: requestConsumer
      destination: request
      consumer:
        headerMode: raw
        useNativeDecoding: true
    validate:
      group: validateConsumer
      destination: validate
      consumer:
        headerMode: raw
        useNativeDecoding: true
  kafka:
    streams:
      binder:
        brokers: localhost:9093
        configuration:
          schema.registry.url: http://localhost:8081
          default:
            key:
              serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value:
              serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde


server:
  port: 8080